name 'batsception'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures batsception'
long_description 'Installs/Configures batsception'
version '0.1.0'
